export const mockBooks = [
  {
    id: 1,
    code: '978-1-234567-00-1',
    resourceType: 'Book',
    title: 'Indigenous Healing Practices of the Philippines',
    author: 'Dr. Maria Santos',
    publisher: 'NCIP Publications',
    subject: 'Medicine, Traditional Knowledge',
    datePublished: '2023-01-15',
    copies: 3,
    status: 'Available',
    keywords: 'indigenous, healing, traditional medicine, practices',
    dateAdded: '2024-01-15',
  },
  {
    id: 2,
    code: '978-1-234567-01-8',
    resourceType: 'Book',
    title: 'Oral Traditions and Cultural Heritage',
    author: 'Prof. Juan Dela Cruz',
    publisher: 'Academic Press',
    subject: 'Anthropology, Culture',
    datePublished: '2022-06-10',
    copies: 2,
    status: 'Borrowed',
    keywords: 'oral traditions, culture, indigenous heritage',
    dateAdded: '2024-02-10',
  },
  {
    id: 3,
    code: '978-1-234567-02-5',
    resourceType: 'Book',
    title: 'Indigenous Land Rights and Law',
    author: 'Atty. Rebecca Morales',
    publisher: 'Legal Publishers Inc.',
    subject: 'Law, Land Rights',
    datePublished: '2023-03-20',
    copies: 1,
    status: 'Available',
    keywords: 'land rights, indigenous peoples, law, rights',
    dateAdded: '2024-01-20',
  },
  {
    id: 4,
    code: '978-1-234567-03-2',
    resourceType: 'Book',
    title: 'Traditional Agriculture Methods',
    author: 'Dr. Jose Reyes',
    publisher: 'Agricultural Society Press',
    subject: 'Agriculture, Traditional Practices',
    datePublished: '2021-11-05',
    copies: 4,
    status: 'Reserved',
    keywords: 'agriculture, traditional farming, sustainable practices',
    dateAdded: '2024-02-05',
  },
  {
    id: 5,
    code: '978-1-234567-04-9',
    resourceType: 'Journal',
    title: 'Archaeological Findings in Mindanao',
    author: 'Dr. Elena Torres',
    publisher: 'Archaeological Institute',
    subject: 'Archaeology, History',
    datePublished: '2024-02-01',
    copies: 2,
    status: 'Available',
    keywords: 'archaeology, mindanao, findings, historical',
    dateAdded: '2024-03-01',
  },
]

export const mockMembers = [
  {
    id: 1,
    name: 'Dr. Maria Santos',
    email: 'maria@ncip.gov.ph',
    type: 'Researcher',
    joinDate: '2023-06-15',
    booksCheckedOut: 2,
    status: 'Active',
  },
  {
    id: 2,
    name: 'Prof. Juan Dela Cruz',
    email: 'juan@ncip.gov.ph',
    type: 'Academic',
    joinDate: '2023-07-20',
    booksCheckedOut: 1,
    status: 'Active',
  },
  {
    id: 3,
    name: 'Atty. Rebecca Morales',
    email: 'rebecca@ncip.gov.ph',
    type: 'Researcher',
    joinDate: '2023-08-10',
    booksCheckedOut: 0,
    status: 'Active',
  },
  {
    id: 4,
    name: 'Dr. Jose Reyes',
    email: 'jose@ncip.gov.ph',
    type: 'Researcher',
    joinDate: '2023-09-05',
    booksCheckedOut: 3,
    status: 'Active',
  },
  {
    id: 5,
    name: 'Dr. Elena Torres',
    email: 'elena@ncip.gov.ph',
    type: 'Academic',
    joinDate: '2023-10-12',
    booksCheckedOut: 1,
    status: 'Active',
  },
]

export const mockBorrowingHistory = [
  {
    id: 1,
    memberId: 1,
    bookId: 1,
    borrowDate: '2024-02-01',
    dueDate: '2024-03-01',
    returnDate: null,
    status: 'Active',
  },
  {
    id: 2,
    memberId: 2,
    bookId: 2,
    borrowDate: '2024-02-10',
    dueDate: '2024-03-10',
    returnDate: null,
    status: 'Active',
  },
  {
    id: 3,
    memberId: 1,
    bookId: 3,
    borrowDate: '2024-01-20',
    dueDate: '2024-02-20',
    returnDate: '2024-02-18',
    status: 'Returned',
  },
]

export const mockActivityLog = [
  {
    id: 1,
    action: 'Book borrowed',
    description: 'Dr. Maria Santos borrowed "Indigenous Healing Practices"',
    timestamp: '2024-02-01 10:30 AM',
    type: 'borrow',
  },
  {
    id: 2,
    action: 'New member registered',
    description: 'Dr. Elena Torres joined as Researcher',
    timestamp: '2024-03-01 09:15 AM',
    type: 'member',
  },
  {
    id: 3,
    action: 'Book returned',
    description: 'Dr. Jose Reyes returned "Traditional Agriculture Methods"',
    timestamp: '2024-02-28 02:45 PM',
    type: 'return',
  },
  {
    id: 4,
    action: 'Book reserved',
    description: 'Prof. Juan Dela Cruz reserved "Oral Traditions and Cultural Heritage"',
    timestamp: '2024-02-25 11:20 AM',
    type: 'reserve',
  },
  {
    id: 5,
    action: 'New book added',
    description: 'Archaeological Findings in Mindanao added to collection',
    timestamp: '2024-03-01 08:00 AM',
    type: 'book',
  },
]

export const mockDashboardStats = {
  totalBooks: 156,
  availableBooks: 98,
  borrowedBooks: 42,
  reservedBooks: 16,
  activeMembers: 34,
  pendingReturns: 8,
}

export const mockArchiveItems = [
  {
    id: 1,
    title: 'Ifugao Rice Terrace Documentation',
    type: 'Oral History',
    date: '2023-01-15',
    content: 'Audio recording of traditional Ifugao farming techniques',
    contributor: 'Dr. Maria Santos',
  },
  {
    id: 2,
    title: 'Cordillera Weaving Techniques',
    type: 'Video',
    date: '2023-02-20',
    content: 'Visual documentation of traditional weaving methods',
    contributor: 'Prof. Juan Dela Cruz',
  },
  {
    id: 3,
    title: 'Mindanao Indigenous Rituals',
    type: 'Written Documentation',
    date: '2023-03-10',
    content: 'Comprehensive notes on traditional ceremonial practices',
    contributor: 'Atty. Rebecca Morales',
  },
]

export const mockReports = [
  {
    id: 1,
    title: 'Monthly Circulation Report - February 2024',
    date: '2024-02-29',
    type: 'Circulation',
    status: 'Published',
  },
  {
    id: 2,
    title: 'Collection Development Review',
    date: '2024-02-15',
    type: 'Collection',
    status: 'Draft',
  },
  {
    id: 3,
    title: 'Member Engagement Analytics',
    date: '2024-01-31',
    type: 'Analytics',
    status: 'Published',
  },
]

export const mockUsers = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@ncip-library.gov.ph',
    role: 'Administrator',
    phone: '+63-2-8123-4567',
    department: 'Administration',
    joinDate: '2023-01-01',
    status: 'Active',
    profileImage: null,
  },
  {
    id: 2,
    name: 'John Smith',
    email: 'user@ncip-library.gov.ph',
    role: 'Librarian',
    phone: '+63-917-123-4567',
    department: 'Cataloging',
    joinDate: '2023-06-15',
    status: 'Active',
    profileImage: null,
  },
  {
    id: 3,
    name: 'Guest User',
    email: 'guest@ncip-library.gov.ph',
    role: 'Guest',
    phone: '+63-917-999-9999',
    department: 'Public Access',
    joinDate: '2024-02-09',
    status: 'Active',
    profileImage: null,
  },
]

export const mockUserDashboard = {
  borrowedBooks: [
    {
      id: 1,
      title: 'Indigenous Healing Practices of the Philippines',
      author: 'Dr. Maria Santos',
      borrowDate: '2024-02-01',
      dueDate: '2024-03-01',
      status: 'Active',
    },
    {
      id: 2,
      title: 'Oral Traditions and Cultural Heritage',
      author: 'Prof. Juan Dela Cruz',
      borrowDate: '2024-01-20',
      dueDate: '2024-02-20',
      status: 'Overdue',
    },
  ],
  reservedBooks: [
    {
      id: 5,
      title: 'Traditional Agriculture Methods',
      author: 'Dr. Jose Reyes',
      reserveDate: '2024-02-05',
      position: 2,
    },
  ],
  recentActivities: [
    {
      id: 1,
      action: 'Borrowed',
      item: 'Indigenous Healing Practices',
      date: '2024-02-01',
    },
    {
      id: 2,
      action: 'Reserved',
      item: 'Traditional Agriculture Methods',
      date: '2024-02-05',
    },
    {
      id: 3,
      action: 'Returned',
      item: 'Indigenous Land Rights and Law',
      date: '2024-01-30',
    },
  ],
}
